# Generated by Django 5.0 on 2025-10-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petition_images/'),
        ),
    ]
